### ISSUE TITLE
Windows executable

### ISSUE THREAD

**Issue by specke** [svendahl/cap#1]
I tested your new compressor v.1.2 on my corpus and am massively impressed with the increased compression ratio. I am seeing 0.8% improvement on the compression ratio in comparison with the previous best compressor by r57shell, which in itself was about 0.7% better than the official compressor. At the same time, the compression speed is very good. Given the popularity of ApLib, this is a very useful new tool, which needs a lot more exposure.

I'd like to ask for 2 feature requests. First, the option "e" currently used for compression does not make much sense, so it is very confusing. Second, it would be very great to have official binary builds, at least for windows.

**Comment by dasv18sp** [comment]
The d and e options are for decode and encode respectively but perhaps the next version should have separate applications for that altogether.
I fail to see what purpose binary builds would serve as it is very easy to compile yourself using the Makefile or build.bat
Thanks for the input, much appreciated!
